import './globals.css';
import {Roboto_Flex} from 'next/font/google';

const robotoFlex = Roboto_Flex({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="dark">
      <body className={`${robotoFlex.className} bg-stone text-dark dark:bg-dark-soft`}>
        {children}
      </body>
    </html>
  );
}
