import {ClerkProvider} from '@clerk/nextjs';
import './globals.css';
import {Roboto_Flex} from 'next/font/google';

const robotoFlex = Roboto_Flex({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${robotoFlex.className} bg-stone text-dark dark:bg-dark-soft`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
